import { ChevronRight } from "lucide-react";
import { AuditButton } from "./WebsiteAuditHero";

const problems = [["01", "You look like everyone else", "Your expertise may be different. Your website doesn't make that obvious."], ["02", "Buyers don't get the value", "Complex services, weak messaging, and unclear positioning make prospects work too hard to understand why they should choose you."], ["03", "Traffic doesn't turn into pipeline", "Visitors arrive, browse, and leave because the site isn't engineered around a clear conversion path."]];
const auditCategories = [
  { number: "01", title: "Positioning & messaging", question: "Can a buyer quickly understand what you do, who you help, and why your company is different?", criteria: ["Value proposition", "Service clarity", "ICP alignment", "Differentiation", "Messaging hierarchy"] },
  { number: "02", title: "Credibility & trust", question: "Does the website make your company feel established, capable, and safe to buy from?", criteria: ["Visual credibility", "Social proof", "Case studies", "Trust signals", "Brand consistency"] },
  { number: "03", title: "Conversion path", question: "Does the experience naturally move qualified visitors toward a meaningful next step?", criteria: ["CTA strategy", "Page hierarchy", "User journey", "Lead capture", "Friction points"] },
  { number: "04", title: "UX & performance", question: "Does the site feel fast, modern, clear, and easy to use across devices?", criteria: ["Mobile experience", "Navigation", "Readability", "Page speed signals", "Visual hierarchy"] },
];
const credibilityPillars = [
  { number: "01", title: "Strategy", label: "Positioning • Messaging • Conversion" },
  { number: "02", title: "Design", label: "Brand • UX • Visual hierarchy" },
  { number: "03", title: "Engineering", label: "Performance • Mobile • Implementation" },
];
export function WebsiteAuditProblems() { return <section className="wa-section wa-problems" id="problems"><div className="wa-problems__intro"><p className="wa-eyebrow">The credibility gap</p><h2>Your website may be costing you<br className="wa-problems__desktop-break" /> more than you think.</h2><p>When buyers can't quickly understand your value or trust the experience, qualified opportunities leave before sales ever gets involved.</p></div><div className="wa-problem-diagnosis"><div className="wa-problem-list">{problems.map(([number, title, copy]) => <article className="wa-problem" key={number}><span>{number}</span><div><h3>{title}</h3><p>{copy}</p></div></article>)}</div><div className="wa-comparison"><div><span className="wa-comparison__label">Before</span><BeforeSite /></div><div className="wa-comparison__arrow" aria-hidden="true">→</div><div><span className="wa-comparison__label wa-comparison__label--blue">After</span><AfterSite /></div></div></div></section>; }

function BeforeSite() { return <div className="wa-mini-site wa-mini-site--before"><small>YOUR COMPANY</small><h4>Solutions for the future of business</h4><p>We provide innovative technology solutions for companies of all sizes.</p><span className="wa-mini-site__cta">Learn more</span><div className="wa-mini-site__blocks"><i /><i /><i /></div></div>; }
function AfterSite() { return <div className="wa-mini-site wa-mini-site--after"><small>INFRASTRUCTURE FORWARD</small><h4>Technology operations, <em>without the drag.</em></h4><p>Turn fragmented cloud operations into a clear competitive advantage.</p><span className="wa-mini-site__cta">See how it works <ChevronRight size={13} /></span><div className="wa-mini-site__stat"><span>System clarity</span><b>01 / 01</b></div></div>; }
export function WebsiteAuditOffer({ onCtaClick }: { onCtaClick: (location: string) => void }) { return <section className="wa-audit-deliverables"><div className="wa-audit-deliverables__intro"><p className="wa-eyebrow">What we'll audit</p><h2>We'll show you where your website<br className="wa-audit-deliverables__desktop-break" /> is losing opportunities.</h2><p>We review the parts of your website that directly affect how buyers understand, trust, and take action on your business.</p></div><div className="wa-audit-deliverables__grid">{auditCategories.map((category) => <article className="wa-audit-category" key={category.number}><span>{category.number}</span><h3>{category.title}</h3><p>{category.question}</p><ul aria-label={`${category.title} review criteria`}>{category.criteria.map((criterion) => <li key={criterion}>{criterion}</li>)}</ul></article>)}</div><div className="wa-audit-deliverables__callout"><div><p className="wa-eyebrow">What you'll leave with</p><h3>You don't need more website data.<br />You need to know what to fix.</h3><p>We'll prioritize the highest-impact issues so you know what deserves attention first — and what can wait.</p></div><AuditButton onCtaClick={onCtaClick} location="audit_deliverables">Get my free website audit</AuditButton></div></section>; }

export function WebsiteAuditCredibility() { return <section className="wa-credibility"><div className="wa-credibility__intro"><p className="wa-eyebrow">Why CloudSight</p><h2>Built for companies that sell<br className="wa-credibility__desktop-break" /> complex technology.</h2><p>CloudSight evaluates both the buyer experience and the technical product experience.</p></div><div className="wa-credibility__framework" aria-label="CloudSight audit lenses">{credibilityPillars.map((pillar) => <article key={pillar.number}><span>{pillar.number}</span><h3>{pillar.title}</h3><p>{pillar.label}</p></article>)}</div></section>; }

export function WebsiteAuditProcess() { const steps = [["Send us your site", "Share your website and a few business details."], ["We review it", "We assess the buyer and technical experience."], ["You get the priorities", "See what to fix first and why it matters."]]; return <section className="wa-section wa-process"><p className="wa-eyebrow">How it works</p><h2>From your website<br />to a clear action plan.</h2><div>{steps.map(([title, copy], index) => <article key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{copy}</p></article>)}</div><p className="wa-process__reassurance">No bloated report. No generic score. Just the issues that matter most.</p></section>; }
