import type {
  OrganizationRole,
} from "@prisma/client";

export const ORGANIZATION_PERMISSIONS = {
  ORGANIZATION_MANAGE:
    "organization:manage",

  MEMBERS_MANAGE:
    "members:manage",

  CLOUD_ACCOUNTS_READ:
    "cloud-accounts:read",

  CLOUD_ACCOUNTS_WRITE:
    "cloud-accounts:write",

  COSTS_READ:
    "costs:read",

  BUDGETS_READ:
    "budgets:read",

  BUDGETS_WRITE:
    "budgets:write",

  REPORTS_READ:
    "reports:read",

  REPORTS_WRITE:
    "reports:write",

  ALERTS_READ:
    "alerts:read",
} as const;

export type OrganizationPermission =
  (typeof ORGANIZATION_PERMISSIONS)[keyof typeof ORGANIZATION_PERMISSIONS];

const ROLE_PERMISSIONS: Record<
  OrganizationRole,
  ReadonlySet<OrganizationPermission>
> = {
  OWNER: new Set([
    ORGANIZATION_PERMISSIONS.ORGANIZATION_MANAGE,
    ORGANIZATION_PERMISSIONS.MEMBERS_MANAGE,

    ORGANIZATION_PERMISSIONS.CLOUD_ACCOUNTS_READ,
    ORGANIZATION_PERMISSIONS.CLOUD_ACCOUNTS_WRITE,

    ORGANIZATION_PERMISSIONS.COSTS_READ,

    ORGANIZATION_PERMISSIONS.BUDGETS_READ,
    ORGANIZATION_PERMISSIONS.BUDGETS_WRITE,

    ORGANIZATION_PERMISSIONS.REPORTS_READ,
    ORGANIZATION_PERMISSIONS.REPORTS_WRITE,

    ORGANIZATION_PERMISSIONS.ALERTS_READ,
  ]),

  ADMIN: new Set([
    ORGANIZATION_PERMISSIONS.MEMBERS_MANAGE,

    ORGANIZATION_PERMISSIONS.CLOUD_ACCOUNTS_READ,
    ORGANIZATION_PERMISSIONS.CLOUD_ACCOUNTS_WRITE,

    ORGANIZATION_PERMISSIONS.COSTS_READ,

    ORGANIZATION_PERMISSIONS.BUDGETS_READ,
    ORGANIZATION_PERMISSIONS.BUDGETS_WRITE,

    ORGANIZATION_PERMISSIONS.REPORTS_READ,
    ORGANIZATION_PERMISSIONS.REPORTS_WRITE,

    ORGANIZATION_PERMISSIONS.ALERTS_READ,
  ]),

  MEMBER: new Set([
    ORGANIZATION_PERMISSIONS.CLOUD_ACCOUNTS_READ,

    ORGANIZATION_PERMISSIONS.COSTS_READ,

    ORGANIZATION_PERMISSIONS.BUDGETS_READ,

    ORGANIZATION_PERMISSIONS.REPORTS_READ,
    ORGANIZATION_PERMISSIONS.REPORTS_WRITE,

    ORGANIZATION_PERMISSIONS.ALERTS_READ,
  ]),

  VIEWER: new Set([
    ORGANIZATION_PERMISSIONS.CLOUD_ACCOUNTS_READ,

    ORGANIZATION_PERMISSIONS.COSTS_READ,

    ORGANIZATION_PERMISSIONS.BUDGETS_READ,

    ORGANIZATION_PERMISSIONS.REPORTS_READ,

    ORGANIZATION_PERMISSIONS.ALERTS_READ,
  ]),
};

export function organizationRoleHasPermission(
  role: OrganizationRole,
  permission: OrganizationPermission,
): boolean {
  return ROLE_PERMISSIONS[
    role
  ].has(permission);
}